### ISSUE TITLE
Option to add own API key

### ISSUE THREAD

**Issue by sphh** [tmalch/lightningWeather#4]
Does it make sense to add an option where you can add your own API key to be used for downloading the forecast? If a private key is used, please make it configurable how often the forecast is updated.

**Comment by tmalch** [comment]
It makes sense to allow users to use their own developer keys but it is forbidden by the terms of use of all service providers. Therefore I'll not provide a gui for this setting, but there will be a possibility in about:config in an upcoming release.

I don't want to let the user determine the update frequency because then it could be that a single user with an inappropriate short update timeout could consume the whole contingent of requests of a service provider. This would make the addon unusable for all other users.

**Comment by sphh** [comment]
Thank you for your explanations. To be honest, that takes me a bit of a surprise. Other software requires me to my own key. I checked a couple of sites and could not find the terms mentioning that it is forbidden to use one's own developer keys. Do you have links to the relevant licenses?

Yes indeed, it does not make sense to allow to change the frequency if you do not use your own key.

**Comment by tmalch** [comment]
Hi just re-read the terms of service for openweathermap and darksky, 
I haven't found any terms regarding this on openweathermap so yes I exaggerated a bit when I said that all providers forbid it. But darksky makes it quite clear in their terms of use:
"Your permission to use the Service is condition upon your agreement that you will not ..... direct your end-users to sign up for their own API account (The Dark Sky API not intended to be used directly by end-users);" [https://darksky.net/dev/docs/terms]
